# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.gh_pages }}
        ssh-host: github.com

    # Runs the docusaurus publish script
    - name: Run ducusaurus publish script
      run: |
        git config --global user.name "Action Jackson"
        git config --global user.email "actions@joincolony.github.io"
        sudo npm install --global docusaurus-init
        npm install
        # crowdin install
        sudo apt-get install default-jre
        wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
        sudo dpkg -i crowdin.deb
        # translations upload/download
        crowdin upload sources --auto-update -b master
        crowdin download -b master
        # build and publish website
        GIT_USER=joincolony.github.io CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages
      working-directory: ./website
